# ~/.bashrc: executed by bash(1) for non-login shells.

# Note: PS1 and umask are already set in /etc/profile. You should not
# need this unless you want different defaults for root.
# PS1='${debian_chroot:+($debian_chroot)}\h:\w\$ '
# umask 022
export PATH=$PATH:/opt/lampp/bin

# You may uncomment the following lines if you want `ls' to be colorized:
export LS_OPTIONS='--color=auto'
export SHELL=bash

eval "`dircolors`"
alias ls='ls $LS_OPTIONS'
alias ll='ls $LS_OPTIONS -alF'
alias l='ls $LS_OPTIONS -lA'
PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '
#
# Some more alias to avoid making mistakes:
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'

HISTCONTROL=ignoreboth

# append to the history file, don't overwrite it
shopt -s histappend
PROMPT_COMMAND="history -a;$PROMPT_COMMAND"

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
HISTSIZE=20000
HISTFILESIZE=20000

alias flush="echo -n > /opt/lampp/htdocs/system/logs/log-$(date "+%Y-%m-%d").php"
alias log="less /opt/lampp/htdocs/system/logs/log-$(date "+%Y-%m-%d").php"
# /opt/lampp/bin/mysql -u root --socket /opt/lampp/htdocs/mysql/mysql.sock -e "create database ik_game;"
alias mysql="mysql -u root --socket /opt/lampp/htdocs/mysql/mysql.sock ik_game"